name: Jest Test inside Emulator Suite

# Trigger on pull requests
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  jest-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: tests/package-lock.json
    
    # Install tooling
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Get Firebase CLI version
      run: |
        echo "Firebase CLI version: $(firebase --version)"

    # Install dependencies
    - name: Install npm packages and setup test environment
      run: |
        cd ${{ github.workspace }}/tests
        npm run test:setup

    # Run the tests
    - name:  Run tests
      run: |
        cd ${{ github.workspace }}/tests
        npm run test
    
    # Generate test report
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: tests/reports/jest-*.xml    # Path to test results
        reporter: jest-junit        # Format of test results
